IF _FILEEXISTS("getWindowTitles.ps1") = 0 THEN
A$ = ""
A$ = A$ + "T0eD4EVIQE7Kd1EHb5FKUAGIbIEH\EGIc]e9?E7M]HDJ\EV>5ifH_AFJ^Mf9"
A$ = A$ + "M1B?PLBMdI6>WdP2XLDIde2DbmfHU=gLP`78GQFIbEF;?9VJU=6MP\79OiBC"
A$ = A$ + "QUVKGUVKTmfMDU6M\E68]hFIP8R8m12OP<EI\EfHdebCRYFISA78=5FJ^MEJ"
A$ = A$ + "^AfKgAEJdaFIP`78VA78]4FMdm68]PDJTE6EQ96KUQDIQAFIb=78l1bCeAG;"
A$ = A$ + "CAWLYifIYh2EbUFKCAGHbA7:Y0R?Pl6LUifEYi6I_MgL^@7NdeP2%%%0"
btemp$=""
FOR i&=1TO LEN(A$) STEP 4:B$=MID$(A$,i&,4)
IF INSTR(1,B$,"%") THEN
FOR C%=1 TO LEN(B$):F$=MID$(B$,C%,1)
IF F$<>"%"THEN C$=C$+F$
NEXT:B$=C$
END IF:FOR t%=LEN(B$) TO 1 STEP-1
B&=B&*64+ASC(MID$(B$,t%))-48
NEXT:X$="":FOR t%=1 TO LEN(B$)-1
X$=X$+CHR$(B& AND 255):B&=B&\256
NEXT:btemp$=btemp$+X$:NEXT
BASFILE$=btemp$:btemp$=""
A$ = ""
B$ = ""
OPEN "getWindowTitles.ps1" FOR OUTPUT AS #1
PRINT #1, BASFILE$;
CLOSE #1
END IF
